### ISSUE TITLE
About the pose metric

### ISSUE THREAD

**Issue by wangjiyuan9** [antabangun/DualRefine#5]
I'd use this [repo](https://github.com/Huangying-Zhan/kitti-odom-eval) to evaluate the pose model of monodepth2. However, after I used the 7dof alignment, I got this result:
``
Sequence: 9
Translational error (%):  106.8673984505003
Rotational error (deg/100m):  31.512737620641563
ATE (m):  36.975670632294786
RPE (m):  2.0602305237673226
RPE (deg):  1.3713156131743185
``
The unit is totally same with your paper but have a huge difference on Terr, Rerr, and ATE.

So, I'd like to ask:
Which monodepth2 do you use for the paper result? How can I reproduce these results? Which repo or tools have you used?

**Comment by wangjiyuan9** [comment]
The other alignment got worse results!

**Comment by antabangun** [comment]
Yes, that repo could be used to evaluate with 7dof alignment. We used the [evo](https://github.com/MichaelGrupp/evo) package, but the results should be similar.

We used the values reported from this [paper](https://arxiv.org/pdf/2105.11610) (Table 3) for monodepth2 VO results.
How does the plot of the GT and Est trajectories look?

If the question is on DualRefine VO results instead of monodepth2, please see this discussion #2.

**Comment by wangjiyuan9** [comment]
![image](https://github.com/antabangun/DualRefine/assets/47146885/9cad5072-8950-46ed-842a-ec93dc91b897)
The trajectories of monodepth2, resnet18, 640 \* 192

**Comment by wangjiyuan9** [comment]
For the evo package, I only find the ate calculation. I think there may be some details I ignored, I will check it.

**Comment by antabangun** [comment]
I think you're right, evo may only provide ape. We might have used evo for another project. I don't remember which eval kit we used for this as it has been a while.

**Comment by wangjiyuan9** [comment]
OK, thank you a lot for your patient answer!
