### ISSUE TITLE
About the function project3d

### ISSUE THREAD

**Issue by wangjiyuan9** [antabangun/DualRefine#7]
Dear Author:
Thank you for your contribution. I'm now analyzing your code. I found that there is a difference between your code and the other one:
[here](https://github.com/antabangun/DualRefine/blob/d311514fb6e017d889af32207b8e5f61fa49a202/dualrefine/layers.py#L204C28-L226C26) and [monodepth2](https://github.com/nianticlabs/monodepth2/blob/b676244e5a1ca55564eb5d16ab521a48f823af31/layers.py#L190-L192)
There is a different result of these two implements:
assume the coord=[0,0],w=h=2
Your code got [0.5,0.5] and monodepth2 got [1,1].
Could you please give me some explanation?

**Comment by wangjiyuan9** [comment]
Note, that monodepth2 is just an example,  almost all the other MDE framework use the other way

**Comment by antabangun** [comment]
I believe that Monodepth2 used the function `F.grid_sample` with the assumption of the `align_corners=True` argument because as noted in Pytorch documentation: 

> The default behavior up to version 1.2.0 was align_corners = True

In our case, we wanted to use `align_corners=False` since it is the recommended way to use `grid_sample` for multiple scales. 

Monodepth2 follows the correct way to compute the pixel coordinates for `align_corners=True`, and we made adjustments to compute the pixel coordinates for the use case of `align_corners=False`.

**Comment by wangjiyuan9** [comment]
Oh, I see! This insight is truly profound. Thank you for your clarification!!!
